version: 0.2
# buidspec used to build docker image and push to ECR
env:
  secrets-manager:
    DOCKERHUB_USERNAME: codebuild/docker:username
    DOCKERHUB_PASSWORD: codebuild/docker:password
    GITHUB_TOKEN: codebuild/gitops:pat
phases:
  install:
    runtime-versions:
        java: corretto21
    commands:
        - echo "install ya command line utility..."
        - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        - chmod +x /usr/bin/yq
        - yq --version
  pre_build:
    commands:
        - aws --version
        - java --version
        - echo "ecr login...."
        - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        - echo "dockerhub login...."
        - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        - echo commit hash is $COMMIT_HASH
        - IMAGE_TAG=${COMMIT_HASH:=latest}
        - echo Image Tag is $IMAGE_TAG
        - echo $CODEBUILD_SRC_DIR
  build:
    commands:
        - java -version
        - echo "building cloud-config-server..."
        - cd $CODEBUILD_SRC_DIR/spring-cloud-k8
        - mvn clean package -pl cloud-config-server -am -DskipTests
        - cd $CODEBUILD_SRC_DIR/spring-cloud-k8/cloud-config-server
        - docker build -t cloud-config-server:latest -f CICD/Dockerfile .
        - docker tag cloud-config-server:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
        - echo Pushing the Docker images...
        - docker push $REPOSITORY_URI:$IMAGE_TAG
        - printf '[{"name":"cloud-config-server", "imageUri":"%s:%s"}]' $REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
        - echo "pushed to ecr successfully"
        - pwd
        - echo "update the image tag in the GitOps repository"
        - cd $CODEBUILD_SRC_DIR
        - cd ..
        ## Setup git identity
        - git config --global user.email "codebuild@amazon.com"
        - git config --global user.name "codebuild"
        - echo "cloning the gitops repo"
        - git clone https://x-token-auth:$GITHUB_TOKEN@github.com/btamilselvan/argocd-trocks-apps.git
        - cd argocd-trocks-apps
        # update the tag name
        - yq -i ".image.tag = \"$IMAGE_TAG\"" apps/cloud-config-server/values.yaml
        - git add apps/cloud-config-server/values.yaml
        - git commit -m "chore(cd) - update cloud-config-server image tag to $IMAGE_TAG [skip ci]"
        - git push origin develop
artifacts:
  base-directory: spring-cloud-k8/cloud-config-server
  files:
    - imagedefinitions.json
cache:
  paths:
     - '/root/.m2/**/*'